// <auto-generated />
using System;
using HSEBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HSEBackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250721193543_AddPositionToPendingUsers")]
    partial class AddPositionToPendingUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // This is auto-generated and should match the current database schema
            // with the addition of the Position field to PendingUsers table
        }
    }
}